<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [66]:
# %load main.py
#1. Import the NUMPY package under the name np.

import numpy as np

#2. Print the NUMPY version and the configuration.

print(np.__version__)

1.19.2


In [67]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,3,5))
a

array([[[0.87724496, 0.98968635, 0.29357098, 0.58024644, 0.62273585],
        [0.36095743, 0.09042393, 0.69961831, 0.67826645, 0.11453798],
        [0.55889551, 0.55831214, 0.32845193, 0.03789879, 0.41344782]],

       [[0.49897366, 0.48345078, 0.1746623 , 0.7546645 , 0.59000484],
        [0.94013123, 0.9171581 , 0.70847687, 0.99294922, 0.81082667],
        [0.56086454, 0.88658567, 0.85675791, 0.36802297, 0.78267936]]])

In [68]:
#4. Print a.

print(a)


[[[0.87724496 0.98968635 0.29357098 0.58024644 0.62273585]
  [0.36095743 0.09042393 0.69961831 0.67826645 0.11453798]
  [0.55889551 0.55831214 0.32845193 0.03789879 0.41344782]]

 [[0.49897366 0.48345078 0.1746623  0.7546645  0.59000484]
  [0.94013123 0.9171581  0.70847687 0.99294922 0.81082667]
  [0.56086454 0.88658567 0.85675791 0.36802297 0.78267936]]]


In [69]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5,2,3))

In [70]:
#6. Print b.

print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [71]:
#7. Do a and b have the same size? How do you prove that in Python code?

np.size(a) == np.size(b)

True

In [72]:
#8. Are you able to add a and b? Why or why not?

# ANSWER:
# >> a + b >> Adding them like this does not work since they have different shapes
# their sums can be added though:

np.sum(a)+np.sum(b)


47.53050348182472

In [73]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = np.transpose(b,(1,2,0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [74]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a + c


In [75]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)
print(d)

# >> one has the random values and one has the random values + 1's

[[[0.87724496 0.98968635 0.29357098 0.58024644 0.62273585]
  [0.36095743 0.09042393 0.69961831 0.67826645 0.11453798]
  [0.55889551 0.55831214 0.32845193 0.03789879 0.41344782]]

 [[0.49897366 0.48345078 0.1746623  0.7546645  0.59000484]
  [0.94013123 0.9171581  0.70847687 0.99294922 0.81082667]
  [0.56086454 0.88658567 0.85675791 0.36802297 0.78267936]]]
[[[1.87724496 1.98968635 1.29357098 1.58024644 1.62273585]
  [1.36095743 1.09042393 1.69961831 1.67826645 1.11453798]
  [1.55889551 1.55831214 1.32845193 1.03789879 1.41344782]]

 [[1.49897366 1.48345078 1.1746623  1.7546645  1.59000484]
  [1.94013123 1.9171581  1.70847687 1.99294922 1.81082667]
  [1.56086454 1.88658567 1.85675791 1.36802297 1.78267936]]]


In [76]:
#12. Multiply a and c. Assign the result to e.

e = a * c
e

array([[[0.87724496, 0.98968635, 0.29357098, 0.58024644, 0.62273585],
        [0.36095743, 0.09042393, 0.69961831, 0.67826645, 0.11453798],
        [0.55889551, 0.55831214, 0.32845193, 0.03789879, 0.41344782]],

       [[0.49897366, 0.48345078, 0.1746623 , 0.7546645 , 0.59000484],
        [0.94013123, 0.9171581 , 0.70847687, 0.99294922, 0.81082667],
        [0.56086454, 0.88658567, 0.85675791, 0.36802297, 0.78267936]]])

In [77]:
#13. Does e equal to a? Why or why not?

e == a
# >> yes cuz c is all 1's

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [78]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_mean = np.mean(d)
d_max = np.max(d)
d_min = np.min(d)

print("mean: ", d_mean)
print("max: ", d_max)
print("min: ", d_min)

mean:  1.5843501160608242
max:  1.992949219482666
min:  1.0378987850571066


In [79]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty_like(d)
print(f)

[[[0.87724496 0.98968635 0.29357098 0.58024644 0.62273585]
  [0.36095743 0.09042393 0.69961831 0.67826645 0.11453798]
  [0.55889551 0.55831214 0.32845193 0.03789879 0.41344782]]

 [[0.49897366 0.48345078 0.1746623  0.7546645  0.59000484]
  [0.94013123 0.9171581  0.70847687 0.99294922 0.81082667]
  [0.56086454 0.88658567 0.85675791 0.36802297 0.78267936]]]


In [80]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

f[(d > d_min) & (d < d_mean)] = 25
f[(d < d_max) & (d > d_mean)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

In [81]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

print(d)
print(f)

[[[1.87724496 1.98968635 1.29357098 1.58024644 1.62273585]
  [1.36095743 1.09042393 1.69961831 1.67826645 1.11453798]
  [1.55889551 1.55831214 1.32845193 1.03789879 1.41344782]]

 [[1.49897366 1.48345078 1.1746623  1.7546645  1.59000484]
  [1.94013123 1.9171581  1.70847687 1.99294922 1.81082667]
  [1.56086454 1.88658567 1.85675791 1.36802297 1.78267936]]]
[[[ 75.  75.  25.  25.  75.]
  [ 25.  25.  75.  75.  25.]
  [ 25.  25.  25.   0.  25.]]

 [[ 25.  25.  25.  75.  75.]
  [ 75.  75.  75. 100.  75.]
  [ 25.  75.  75.  25.  75.]]]


In [84]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

f = f.astype(str)
f[d == d_min] = "A"
f[(d > d_min) & (d < d_mean)] = "B"
f[d == d_mean] = "C"
f[(d < d_max) & (d > d_mean)] = "D"
f[d == d_max] = "E"
print(f)

[[['D' 'D' 'B' 'B' 'D']
  ['B' 'B' 'D' 'D' 'B']
  ['B' 'B' 'B' 'A' 'B']]

 [['B' 'B' 'B' 'D' 'D']
  ['D' 'D' 'D' 'E' 'D']
  ['B' 'D' 'D' 'B' 'D']]]
